export const TASKS_IDS = {
	NAME_ATTRIBUTE: "NAME_ATTRIBUTE",
	INNER_HTML_FORBIDDEN: "INNER_HTML_FORBIDDEN",
	WARNING: "WARNING",
};

export const STATUSES = {
	IDLE: "IDLE",
	CHECKING: "CHECKING",
	COMPLETED: "COMPLETED",
	NOT_COMPLETED: "NOT_COMPLETED",
};
